CRITICAL - 2020-12-27 00:00:07 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::select()
#0 C:\xampp\htdocs\codeigniterfour\app\Controllers\Users.php(16): App\Models\Users_model->getAllCategories()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSession()
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-12-27 00:01:53 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::select()
#0 C:\xampp\htdocs\codeigniterfour\app\Controllers\Users.php(16): App\Models\Users_model->getAllCategories()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSession()
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-12-27 00:01:54 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::select()
#0 C:\xampp\htdocs\codeigniterfour\app\Controllers\Users.php(16): App\Models\Users_model->getAllCategories()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSession()
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-12-27 00:05:05 --> Unable to connect to the database.
#0 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\codeigniterfour\app\Models\Users_model.php(11): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\codeigniterfour\app\Controllers\Users.php(16): App\Models\Users_model->getAllCategories()
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSession()
#5 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#6 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-12-27 00:06:55 --> Call to undefined method CodeIgniter\Database\MySQLi\Result::result()
#0 C:\xampp\htdocs\codeigniterfour\app\Controllers\Users.php(16): App\Models\Users_model->getAllCategories()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSession()
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-12-27 00:08:40 --> Call to undefined method CodeIgniter\Database\MySQLi\Builder::getResult()
#0 C:\xampp\htdocs\codeigniterfour\app\Controllers\Users.php(16): App\Models\Users_model->getAllCategories()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSession()
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-12-27 00:08:56 --> Call to undefined method CodeIgniter\Database\MySQLi\Builder::getResult()
#0 C:\xampp\htdocs\codeigniterfour\app\Controllers\Users.php(16): App\Models\Users_model->getAllCategories()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSession()
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-12-27 00:09:37 --> Call to a member function table() on null
#0 C:\xampp\htdocs\codeigniterfour\app\Controllers\Users.php(16): App\Models\Users_model->getAllCategories()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSession()
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-12-27 00:10:35 --> Call to undefined method CodeIgniter\Database\MySQLi\Result::result()
#0 C:\xampp\htdocs\codeigniterfour\app\Controllers\Users.php(16): App\Models\Users_model->getAllCategories()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSession()
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-12-27 00:21:35 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Common.php(845): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\codeigniterfour\app\Controllers\Users.php(9): redirect('/user/createuse...')
#3 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->index()
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#5 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-12-27 00:23:39 --> Call to a member function userdata() on null
#0 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSession()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-12-27 00:23:56 --> Call to a member function userdata() on null
#0 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSession()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-12-27 00:24:11 --> Call to undefined method CodeIgniter\Session\Session::userdata()
#0 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSession()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-12-27 00:24:21 --> Call to a member function view() on null
#0 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSession()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-12-27 00:31:55 --> Call to a member function userdata() on null
#0 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSessionAdd()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-12-27 00:34:08 --> Cannot call constructor
#0 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(890): App\Controllers\Users->__construct()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-12-27 00:34:24 --> Call to a member function get() on null
#0 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSessionAdd()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-12-27 00:34:51 --> Call to a member function get() on null
#0 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSession()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-12-27 00:35:33 --> A non-numeric value encountered
#0 C:\xampp\htdocs\codeigniterfour\app\Controllers\Users.php(41): CodeIgniter\Debug\Exceptions->errorHandler(2, 'A non-numeric v...', 'C:\\xampp\\htdocs...', 41, Array)
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSessionAdd()
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-12-27 00:36:50 --> A non-numeric value encountered
#0 C:\xampp\htdocs\codeigniterfour\app\Controllers\Users.php(41): CodeIgniter\Debug\Exceptions->errorHandler(2, 'A non-numeric v...', 'C:\\xampp\\htdocs...', 41, Array)
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSessionAdd()
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-12-27 00:39:24 --> Call to a member function set_userdata() on null
#0 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSessionAdd()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-12-27 00:40:11 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Common.php(845): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\codeigniterfour\app\Controllers\Users.php(83): redirect('/user/createuse...')
#3 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSessionAdd()
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#5 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-12-27 00:40:24 --> Call to a member function userdata() on null
#0 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSessionAdd()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-12-27 00:40:47 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Common.php(845): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\codeigniterfour\app\Controllers\Users.php(83): redirect('/user/createuse...')
#3 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSessionAdd()
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#5 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-12-27 00:41:02 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Common.php(845): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\codeigniterfour\app\Controllers\Users.php(83): redirect('/user/createuse...')
#3 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSessionAdd()
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#5 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-12-27 01:25:06 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::insert()
#0 C:\xampp\htdocs\codeigniterfour\app\Controllers\Users.php(104): App\Models\Users_model->submitAllSession(Array)
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->submitAllSession()
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-12-27 01:31:07 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::insertBatch()
#0 C:\xampp\htdocs\codeigniterfour\app\Controllers\Users.php(104): App\Models\Users_model->submitAllSession(Array)
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->submitAllSession()
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-12-27 01:33:42 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::insertBatch()
#0 C:\xampp\htdocs\codeigniterfour\app\Controllers\Users.php(104): App\Models\Users_model->submitAllSession(Array)
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->submitAllSession()
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-12-27 01:33:59 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::insertBatch()
#0 C:\xampp\htdocs\codeigniterfour\app\Controllers\Users.php(104): App\Models\Users_model->submitAllSession(Array)
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->submitAllSession()
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-12-27 01:34:16 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::insert()
#0 C:\xampp\htdocs\codeigniterfour\app\Controllers\Users.php(104): App\Models\Users_model->submitAllSession(Array)
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->submitAllSession()
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-12-27 03:04:40 --> Call to undefined method App\Controllers\Users::validator()
#0 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSessionAdd()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-12-27 03:05:38 --> Call to undefined method App\Controllers\Users::validator()
#0 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSessionAdd()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-12-27 03:05:41 --> Call to undefined method App\Controllers\Users::validator()
#0 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSessionAdd()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-12-27 03:19:13 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\codeigniterfour\app\Views\users\create_user_session.php(51): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 51, Array)
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('users\\create_us...', Array, true)
#3 C:\xampp\htdocs\codeigniterfour\app\Controllers\Users.php(47): view('users\\create_us...', Array)
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSessionAdd()
#5 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#6 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-12-27 03:20:38 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\codeigniterfour\app\Views\users\create_user_session.php(51): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 51, Array)
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('users\\create_us...', Array, true)
#3 C:\xampp\htdocs\codeigniterfour\app\Controllers\Users.php(47): view('users\\create_us...', Array)
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSessionAdd()
#5 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#6 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-12-27 03:21:49 --> Call to a member function getAllCategories() on null
#0 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSessionAdd()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-12-27 03:22:13 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\codeigniterfour\app\Views\users\create_user_session.php(51): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 51, Array)
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('users\\create_us...', Array, true)
#3 C:\xampp\htdocs\codeigniterfour\app\Controllers\Users.php(49): view('users\\create_us...', Array, Array)
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSessionAdd()
#5 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#6 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-12-27 03:22:48 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\codeigniterfour\app\Views\users\create_user_session.php(51): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 51, Array)
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('users\\create_us...', Array, true)
#3 C:\xampp\htdocs\codeigniterfour\app\Controllers\Users.php(49): view('users\\create_us...', Array)
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSessionAdd()
#5 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#6 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-12-27 03:39:39 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\codeigniterfour\app\Views\users\create_user_session.php(51): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 51, Array)
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('users\\create_us...', Array, true)
#3 C:\xampp\htdocs\codeigniterfour\app\Controllers\Users.php(49): view('users\\create_us...', Array)
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSessionAdd()
#5 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#6 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-12-27 03:45:44 --> Call to a member function listErrors() on string
#0 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\View\View.php(246): include()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('users\\create_us...', Array, true)
#2 C:\xampp\htdocs\codeigniterfour\app\Controllers\Users.php(49): view('users\\create_us...', Array)
#3 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSessionAdd()
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#5 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-12-27 03:46:29 --> syntax error, unexpected '}', expecting ';' or ','
#0 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('users\\create_us...', Array, true)
#1 C:\xampp\htdocs\codeigniterfour\app\Controllers\Users.php(27): view('users\\create_us...', Array)
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSession()
#3 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2020-12-27 04:38:54 --> Call to a member function listErrors() on string
#0 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\View\View.php(246): include()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('users\\create_us...', Array, true)
#2 C:\xampp\htdocs\codeigniterfour\app\Controllers\Users.php(53): view('users\\create_us...', Array)
#3 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSessionAdd()
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#5 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-12-27 06:19:54 --> Call to a member function isValid() on null
#0 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->fileUpload()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-12-27 22:11:38 --> Unable to connect to the database.
#0 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\codeigniterfour\app\Models\Users_model.php(11): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\codeigniterfour\app\Controllers\Users.php(28): App\Models\Users_model->getAllCategories()
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSession()
#5 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#6 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-12-27 22:11:42 --> Unable to connect to the database.
#0 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\codeigniterfour\app\Models\Users_model.php(11): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\codeigniterfour\app\Controllers\Users.php(28): App\Models\Users_model->getAllCategories()
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->createUserUsingSession()
#5 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#6 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-12-27 23:46:40 --> Call to a member function getRows() on null
#0 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->showDataTableAjax()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-12-27 23:48:09 --> Call to a member function getRows() on null
#0 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->showDataTableAjax()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-12-27 23:49:04 --> Call to a member function getRows() on null
#0 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->showDataTableAjax()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-12-27 23:49:26 --> Call to a member function getRows() on null
#0 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->showDataTableAjax()
#1 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#2 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\codeigniterfour\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\codeigniterfour\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
